# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy the source code
COPY . ./

# Build the project
RUN npm run build

# Expose ports if needed (not necessary for stdio communication)

# Run the MCP server
CMD ["node", "build/index.js"]
